.Dd $Mdocdate$
.Dt SHELL 1
.Os
.Sh NAME
.Nm shell
.Nd Creates a temporary interactive shell session in a disposable working directory
.Sh SYNOPSIS
.Nm shell
.Op Fl d Ar directory | Fl k
.Op Ar shell
.Sh DESCRIPTION
The
.Nm
utility creates an interactive shell session with a clean environment
and with an empty working directory.
.Pp
By specifying a specific
.Ar shell
on the command line, a shell other than the user's login shell may be
invoked.
If a specific shell is not requested, the
.Ev SHELL
environment variable will be used to infer what shell to start.
.Pp
The basename of the named
.Ar shell
must correspond to a valid login shell and the actual shell that is
started will always be taken from the list of valid login shells (by
matching the basename of the specified
.Ar shell ,
or
.Ev $SHELL ,
against the basenames of
the allowed login shells).
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d Ar directory
Use the specified directory rather than a new temporary directory.
If the directory does not already exist, it will be created.
This directory will not be deleted when the shell session terminates.
This option implies the
.Fl k
option.
.It Fl k
Keep the temprorary directory around after terminating the shell session.
.El
.Sh ENVIRONMENT
.Nm
uses the following environment variables:
.Bl -tag -width Ds
.It Ev TMPDIR
Directory in which to create the working directory when the
.Fl d
option is not used.
.It Ev SHELL
Used to determine what shell to start if a specific
.Ar shell
is not specified on the command line.
.El
.Pp
.Nm
clears the environment of the interactive shell that it starts, but
also sets the following environment variables:
.Bl -tag -width Ds
.It Ev HOME
Set to the working directory where the shell is started.
.It Ev PATH
Set to the output of
.Dq Ic getconf PATH .
.It Ev PS1
Set to the string
.Sq $\ 
.Pq dollar-sign and space .
Note that some shells ignore this variable if passed from the parent
environment.
.It Ev SHELL
Set to the absolute path of the real shell executable.
This may be different from the
.Ar shell
mentioned on the command line as the actual shell used will always be
picked from the list of valid login shells.
.It Ev TERM
Carried over from the parent environment.
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa /etc/shells
Used as a source for valid login shells on systems where
.Dq Cm getent shells
does not work.
.El
.Sh EXAMPLES
Start a new shell in a new temporary directory:
.Bd -literal -offset Ds
$ shell
Starting /bin/ksh in /tmp/shell-ksh.lDv4uX48
$ exit
Removing /tmp/shell-ksh.lDv4uX48
.Ed
.Pp
Start a new
.Cm ksh93
shell in a temporary directory:
.Bd -literal -offset Ds
$ shell ksh93
Starting /usr/local/bin/ksh93 in /tmp/shell-ksh93.oct61lxx
myself:/tmp/shell-ksh93.oct61lxx:1$ exit
Removing /tmp/shell-ksh93.oct61lxx
.Ed
.Pp
Start a new
.Cm bash
shell in a specific directory:
.Bd -literal -offset Ds
$ shell -d "$HOME/testing" bash
Starting /usr/local/bin/bash in /home/myself/testing
$ exit
Leaving /home/myself/testing in place
.Ed
.Sh AUTHORS
.An Andreas Kusalananda K\[:a]h\[:a]ri Aq Mt andreas.kahari@nbis.se
.Sh CAVEATS
For Solaris, the list of valid login shells is taken from the
.Xr shells 4
manual on a Solaris 11.3 system.
This is because Solaris lacks
.Dq Cm getent shells
and may also lack the
.Pa /etc/shells
file.
