.Dd $Mdocdate$
.Dt SHELL 1
.Os
.Sh NAME
.Nm shell
.Nd Creates a temporary interactive shell session in a disposable working directory
.Sh SYNOPSIS
.Nm shell
.Op Fl f
.Op Fl q
.Op Fl d Ar directory | Fl k
.Op Ar shell Op Ar ...
.Nm
.Op Fl f
.Op Fl q
.Op Fl s Ar directory
.Op Fl k
.Op Ar shell Op Ar ...
.Nm
.Fl v
.Sh DESCRIPTION
The
.Nm
utility creates an interactive shell session with a clean environment
and with an empty working directory.
.Pp
By specifying a specific
.Ar shell
on the command line, a shell other than the user's login shell may be
invoked.
If a specific shell is not requested, the
.Ev SHELL
environment variable will be used to infer what shell to start.
.Pp
The basename of the named
.Ar shell
must correspond to a valid login shell and the actual shell that is
started will always be taken from the list of valid login shells (by
matching the basename of the specified
.Ar shell ,
or
.Ev $SHELL ,
against the basenames of
the allowed login shells).
This behaviour may be bypassed by using the
.Fl f
command line option.
.Pp
Any operands present after the name of the
.Ar shell
will be passed as is to the shell in question.
.Pp
If
.Nm
(this utility,
.Em not
the interactive shell process) receives the USR1 signal, the temporary
working directory will not be deleted when the shell session terminates
(as if
.Fl k
had been used from the start).
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d Ar directory
Use the specified directory rather than a new temporary directory.
If the directory does not already exist, it will be created.
This directory will not be deleted when the shell session terminates.
This option implies the
.Fl k
option, and conflicts with the
.Fl s
option.
.It Fl f
Force the execution of the given command, even if it is not a valid
login shell on the current system.
.It Fl k
Keep the temporary directory around after terminating the shell session.
.It Fl q
Be quiet.
Don't output informational messages.
.It Fl s Ar directory
Pre-populate the temporary directory with the contents of the named
directory.
This will copy the whole directory structure rooted in the specified
directory to the temporary working directory.
This option conflicts with the
.Fl d
option.
.It Fl v
Output version information and immediately terminate.
.El
.Sh ENVIRONMENT
.Nm
uses the following environment variables:
.Bl -tag -width Ds
.It Ev SHELL
Used to determine what shell to start if a specific
.Ar shell
is not specified on the command line.
If this variable is unset or empty, then
.Cm /bin/sh
will be used instead.
.It Ev SHELL_SKEL
Directory to automatically pre-populate the temporary working directory with.
This environment variable is not used if any of the
.Fl d
or
.Fl s
options are used on the command line.
.It Ev TMPDIR
Directory in which to create the working directory when the
.Fl d
option is not used.
This variable is used by
.Cm mktemp
which will revert to use
.Pa /tmp
if the variable is not set.
.El
.Pp
.Nm
clears the environment of the interactive shell that it starts, but
also sets the following environment variables:
.Bl -tag -width Ds
.It Ev HOME
Set to the working directory where the shell is started.
.It Ev PATH
Set to the output of
.Dq Ic getconf PATH .
.It Ev PS1
Set to the string
.Sq $\ 
.Pq dollar-sign and space .
Note that some shells ignore this variable if passed from the parent
environment.
.It Ev SHELL
Set to the absolute path of the real shell executable.
This may be different from the
.Ar shell
mentioned on the command line as the actual shell used will be picked
from the list of valid login shells (unless
.Fl f
is used).
.It Ev TERM
Carried over from the parent environment.
.El
.Sh FILES
.Bl -tag -width Ds
.It Pa /etc/shells
Used as a source for valid login shells on systems where
.Dq Cm getent shells
does not work.
.El
.Sh EXAMPLES
Start a new shell in a new temporary directory:
.Bd -literal -offset Ds
$ shell
shell: info: Starting /bin/ksh in /tmp/shell-ksh.mJMHFTFE
$ exit
shell: info: Removing /tmp/shell-ksh.mJMHFTFE
.Ed
.Pp
Start a new
.Cm dash
shell in a temporary directory:
.Bd -literal -offset Ds
$ shell dash
shell: info: Starting /usr/local/bin/dash in /tmp/shell-dash.V7zU6EtZ
$ exit
shell: info: Removing /tmp/shell-dash.V7zU6EtZ
.Ed
.Pp
Start a new
.Cm bash
shell in a specific directory:
.Bd -literal -offset Ds
$ shell -d "$HOME/testing" bash
shell: info: Starting /usr/local/bin/bash in /home/myself/testing
$ exit
exit
shell: info: Leaving /home/myself/testing in place
.Ed
.Pp
Start
.Cm ksh
as a login shell and pre-populate the temporary directory with the
contents of
.Pa $HOME/skel .
Note, starting the
.Cm ksh
shell as a login shell will in this case make it execute the
.Pa .profile
file copied from
.Pa $HOME/skel .
.Bd -literal -offset Ds
$ shell -s "$HOME/skel" ksh -l
shell: info: Copying /home/myself/skel into /tmp/shell-ksh.ngEwbcpD
shell: info: Starting /bin/ksh in /tmp/shell-ksh.ngEwbcpD
$ ls -la
total 36
drwxr-xr-x   2 myself  wheel  512 Apr 15 12:55 .
drwxrwxrwt  28 root    wheel  512 Apr 21 14:15 ..
-rw-r--r--   1 myself  wheel   87 Nov  1 19:14 .Xdefaults
-rw-r--r--   1 myself  wheel  771 Feb  9 10:18 .cshrc
-rw-r--r--   1 myself  wheel  101 Nov  1 19:14 .cvsrc
-rw-r--r--   1 myself  wheel  359 Nov  1 19:14 .login
-rw-r--r--   1 myself  wheel  175 Nov  1 19:14 .mailrc
-rw-r--r--   1 myself  wheel  215 Feb  9 10:18 .profile
-rw-r--r--   1 myself  wheel  108 Apr 15 12:50 .vimrc
$ exit
shell: info: Removing /tmp/shell-ksh.ngEwbcpD
.Ed
.Sh SEE ALSO
.Xr mktemp 1
.Sh AUTHORS
.An Andreas Kusalananda K\[:a]h\[:a]ri Aq Mt andreas.kahari@nbis.se
.Sh CAVEATS
For Solaris, the list of valid login shells is taken from the
.Xr shells 4
manual on a vanilla Solaris 11.4 system.
This is because Solaris lacks
.Dq Cm getent shells
and may also lack the
.Pa /etc/shells
file.
The
.Pa /etc/shells
file will still be used if it exists.
